apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-manager
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pipeline-manager
  template:
    metadata:
      labels:
        app: pipeline-manager
    spec:
      containers:
      - image: 839151377425.dkr.ecr.us-east-1.amazonaws.com/codefresh-inc/codefresh/pipeline-manager:master
        name: pipeline-manager
        ports:
        - containerPort: 80
